name: Release sugoi-ui

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the release'
        required: true   

jobs:

  pre-release:
    name: pre-release
    runs-on: ubuntu-latest
    steps:  
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Git config
        run: |
          git config --global user.name "Insee - Domaine Outils Transverses"
          git config --global user.email "dg75-dsi-domaine-outils-transverses@insee.fr"  

      - name: Clone repo
        run: git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}.git
    
      - name: Checkout branch
        run: |
          cd sugoi-ui/
          git checkout -b release-${{ github.event.inputs.version }}

      - name: Prepare current version
        run: yarn version --new-version ${{ github.event.inputs.version }}

      - name: Commit and push new change
        run: |
          git add .
          git commit -sm "[REL] :rocket: prepare new version ${{ github.event.inputs.version }}"
          git push origin prepare-version-${{ github.event.inputs.version }}
          gh pr create --title "[REL] :rocket: prepare new version ${{ github.event.inputs.version }}" --body "[REL] :rocket: prepare new version ${{ github.event.inputs.version }}"

      - name: Install dependencies with Yarn
        run: yarn

      - run: yarn build
        name: Build with Yarn
        
      - uses: papeloto/action-zip@v1
        name: Zip build
        with:
          files: build/
          dest: sugoi-ui-${{ github.event.inputs.version }}-distribution.zip

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          draft: false
          prerelease: false

      - name: Add zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: sugoi-ui-${{ github.event.inputs.version }}-distribution.zip
          asset_name: sugoi-ui-${{ github.event.inputs.version }}-distribution.zip
          asset_content_type: zip

      - name: Prepare next version
        run: yarn version --minor

      - id: get_version
        name: Get next version
        run: echo ::set-output name=VERSION::$(node -p "require('./package.json').version")

      - name: Commit and push new change
        run: |
          git add .
          git commit -sm "[ENH] :sparkles: prepare next version ${{ steps.get_version.outputs.VERSION }}"
          git push origin prepare-version-${{ github.event.inputs.version }}
          