name: Release sugoi-ui

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get_version
        run: echo ::set-output name=VERSION::1.3.4
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Set new version
        run: npm version ${{ steps.get_version.outputs.VERSION }} --no-git-tag-version
      - name: install dependencies 
        run: yarn
      - run: yarn build
        name: create build
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
      - name: Release snapshot
        id: release-snapshot
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false