name: Release sugoi-ui

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the release'
        required: true   

jobs:

  pre-release:
    name: pre-release
    runs-on: ubuntu-latest
    steps:  

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          
      - name: Prepare
        run: |
          git config --global user.name "Insee - Domaine Outils Transverses"
          git config --global user.email "dg75-dsi-domaine-outils-transverses@insee.fr"  
          git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}.git
          cd sugoi-ui/
          git checkout -b release-${{ github.event.inputs.version }}
          yarn version --new-version ${{ github.event.inputs.version }} --message "[REL] :rocket: prepare new version ${{ github.event.inputs.version }}"
          git push origin release-${{ github.event.inputs.version }} -f
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh pr create --title "[REL] :rocket: prepare new version ${{ github.event.inputs.version }}" --body "[REL] :rocket: prepare new version ${{ github.event.inputs.version }}"


  release:
    name: release
    runs-on: ubuntu-latest
    needs: pre-release
    steps:  
      - name: Clone Deployments repo
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}
          ref: release-${{ github.event.inputs.version }}

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies with Yarn
        run: yarn

      - run: yarn build
        name: Build with Yarn
        
      - uses: papeloto/action-zip@v1
        name: Zip build
        with:
          files: build/
          dest: sugoi-ui-${{ github.event.inputs.version }}-distribution.zip

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          draft: false
          prerelease: false

      - name: Add zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: sugoi-ui-${{ github.event.inputs.version }}-distribution.zip
          asset_name: sugoi-ui-${{ github.event.inputs.version }}-distribution.zip
          asset_content_type: zip


  after-release:
    name: after-release
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          git config --global user.name "Insee - Domaine Outils Transverses"
          git config --global user.email "dg75-dsi-domaine-outils-transverses@insee.fr"  
          git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}.git
          cd sugoi-ui/
          git pull
          git checkout release-${{ github.event.inputs.version }}
          yarn version --minor --message "[ENH] :sparkles: prepare next version"
          git push origin release-${{ github.event.inputs.version }}
        
          