name: Release sugoi-ui

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:
    branches:
      - main
   

jobs:
  releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: get_version
        run: echo ::set-output name=VERSION::$(node -p "require('./package.json').version")
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: papeloto/action-zip@v1
        with:
          files: ./
          dest: sugoi-ui-${{ steps.get_version.outputs.VERSION }}-sources.zip 
      - name: install dependencies 
        run: yarn
      - run: yarn build
        name: create build
      - uses: papeloto/action-zip@v1
        with:
          files: build/
          dest: sugoi-ui-${{ steps.get_version.outputs.VERSION }}-build.zip
      - name: Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
      - name: Upload sources
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: sugoi-ui-${{ steps.get_version.outputs.VERSION }}-sources.zip
          asset_name: sugoi-ui-${{ steps.get_version.outputs.VERSION }}-sources.zip
          asset_content_type: zip
      - name: Upload build app
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: sugoi-ui-${{ steps.get_version.outputs.VERSION }}-build.zip
          asset_name: sugoi-ui-${{ steps.get_version.outputs.VERSION }}-build.zip
          asset_content_type: zip


  prepare_next_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: git config user.email "ts-ci@github.com" && git config user.name "ts-ci@github.com"
      - name: Set next version
        run: npm version --no-git-tag-version major 
      - run: git add . && git commit -m "prepare next version" && git push