name: Release sugoi-ui

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
   

jobs:

  build: 
    name: Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2

      - id: get_version
        name: Get version from package.json
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Setup Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies with Yarn
        run: yarn

      - name: Set version
        run: |
          git config --global user.name "Insee - Domaine Outils Transverses"
          git config --global user.email "dg75-dsi-domaine-outils-transverses@insee.fr"  
          yarn version --new-version ${{ steps.get_version.outputs.VERSION }}

      - run: yarn build
        name: Build with Yarn
        
      - uses: papeloto/action-zip@v1
        name: Zip build
        with:
          files: build/
          dest: sugoi-ui-${{ steps.get_version.outputs.VERSION }}-distribution.zip

      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: zip
          path: sugoi-ui-${{ steps.get_version.outputs.VERSION }}-distribution.zip

  releases:
    name: releases
    runs-on: ubuntu-latest
    needs: Build
    steps:

      - name: Checkout zip artifact
        uses: actions/download-artifact@v2
        with:
          name: zip

      - name: Set version
        run: |
          git config --global user.name "Insee - Domaine Outils Transverses"
          git config --global user.email "dg75-dsi-domaine-outils-transverses@insee.fr"  
          yarn version --new-version ${{ needs.build.outputs.version }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.build.outputs.version }}
          release_name: ${{ needs.build.outputs.version }}
          draft: false
          prerelease: false

      - name: Add zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: sugoi-ui-${{ needs.build.outputs.version }}-distribution.zip
          asset_name: sugoi-ui-${{ needs.build.outputs.version }}-distribution.zip
          asset_content_type: zip


  prepare_next_version:
    runs-on: ubuntu-latest
    needs: releases
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}.git
          git config --global user.name "Insee - Domaine Outils Transverses"
          git config --global user.email "dg75-dsi-domaine-outils-transverses@insee.fr"
          cd sugoi-ui        
          git checkout main
          git pull
          yarn version --new-version ${{ needs.build.outputs.version }}
          yarn version --minor
          new_version=$(echo ::set-output name=VERSION::$(node -p "require('./package.json').version"))
          git add .
          git commit -sm"Prepare new version"
          git push origin prepare-version-$new_version
          gh pr create --title "Prepare new version" --body "Prepare new version"